title: Send e-mail via Sendgrid
image: codefreshplugins/sendgridplugin
version: 0.1.0
description: Send e-mail via Sendgrid
categories:
  - Featured
sources:
  - 'https://github.com/codefresh-contrib/sendgridplugin'
icon: 'https://images.ctfassets.net/bx16dovk9m7p/XNo9W4lwAMsai8KOikAae/35f6df5bf800dd4993c2d98376448f0d/a37a5b5ab495b5531dd406d40baa8a5c.png'
maintainers:
  - name: Pavel Kostohrys
envs:
  - name: SENDGRID_APIKEY
    description: 'API key from SendGrid (required)'
  - name: SENDGRID_MAIL
    type: required
    description: 'mail where the letter will be sent, you can use comma divider to send on multiple mails (ex.: mail1@example.com, mail2@exmaple.com)'
  - name: SENDGRID_FROM
    description: 'from header of mail (required)'
  - name: SENDGRID_SUBJECT
    description: 'subject header of mail (required)'
  - name: SENDGRID_TYPE
    description: 'type of mail [build, message, custom] (required)'
  - name: SENDGRID_MESSAGE
    description: Text of message for type message
  - name: SENDGRID_TEMPLATE
    description: Template of message for type message
